#!/bin/bash

#weather=$(curl -s wttr.in/Vejleby?format=%t)
weather=$(cat ~/.config/weather_temp.txt)
wthr=$(sed 24q ~/.config/weather.txt | grep value | awk '{print $2" "$3" "$4" "$5}' | sed 's/"//g')
icon=" "

printf " %s %s %s \n" "$icon " "$wthr"  "$weather"
#🌤️
#
# 
